# jclaravel@gmail.com
# render.yaml
services:
  - type: web
    name: sales-forecast-whatsapp
    env: python
    pythonVersion: "3.12"
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false
